// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * An object that describes changes to a move. These changes should be applied
 * recursively, altering only the specified properties; enhanced arrays should
 * be concatencated with the original array value.
 */
@JsonSerialize
public class MoveEnhancementProgressRoll extends MoveEnhancement {
    @JsonProperty("enhances")
    private List<MoveIdWildcard> enhances;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("trigger")
    private TriggerProgressRollEnhancement trigger;

    public MoveEnhancementProgressRoll() {
    }

    /**
     * Getter for enhances.
     * <p>
     */
    public List<MoveIdWildcard> getEnhances() {
        return enhances;
    }

    /**
     * Setter for enhances.
     * <p>
     */
    public void setEnhances(List<MoveIdWildcard> enhances) {
        this.enhances = enhances;
    }

    /**
     * Getter for trigger.
     * <p>
     */
    public TriggerProgressRollEnhancement getTrigger() {
        return trigger;
    }

    /**
     * Setter for trigger.
     * <p>
     */
    public void setTrigger(TriggerProgressRollEnhancement trigger) {
        this.trigger = trigger;
    }
}
