// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "roll_type", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(name = "action_roll", value = MoveActionRoll.class),
        @JsonSubTypes.Type(name = "no_roll", value = MoveNoRoll.class),
        @JsonSubTypes.Type(name = "progress_roll", value = MoveProgressRoll.class),
        @JsonSubTypes.Type(name = "special_track", value = MoveSpecialTrack.class),
})
public abstract class Move {

    @JsonProperty("roll_type")
    private String rollType;

    public abstract Label getName();

    public abstract MarkdownString getText();

    public String getRollType() {
        return rollType;
    }
}
