// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * The label at the head of each table column. The `roll` key refers to the roll
 * column showing the dice range (`min` and `max` on each table row).
 */
@JsonSerialize
public class OracleCollectionTableSharedTextColumnLabels {
    @JsonProperty("text")
    private Label text;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("text2")
    private Label text2;

    public OracleCollectionTableSharedTextColumnLabels() {
    }

    /**
     * Getter for text.
     * <p>
     */
    public Label getText() {
        return text;
    }

    /**
     * Setter for text.
     * <p>
     */
    public void setText(Label text) {
        this.text = text;
    }

    public Label getText2() {
        return text2;
    }

    public void setText2(Label text2) {
        this.text2 = text2;
    }
}
