// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import java.util.Collection;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "oracle_type")
@JsonSubTypes({
        @JsonSubTypes.Type(name = "OracleTableSharedText3", value = OracleCollectionTableSharedText.class),
        @JsonSubTypes.Type(name = "table_shared_rolls", value = OracleCollectionTableSharedRolls.class),
        @JsonSubTypes.Type(name = "table_shared_text", value = OracleCollectionTableSharedText.class),
        @JsonSubTypes.Type(name = "table_shared_text2", value = OracleCollectionTableSharedText.class),
        @JsonSubTypes.Type(name = "tables", value = OracleCollectionTables.class),
})
public abstract class OracleCollection {
    public abstract Label getName();

    public abstract MarkdownString getSummary();

    public abstract MarkdownString getDescription();

    public abstract String getCollectionType();

    public abstract Map<String, ?> getContents();

    public Collection<OracleTableRollable> rollableTable() {
        if (this instanceof OracleCollectionTables tables) {
            return getContents() == null ? List.of() : tables.getContents().values();
        }
        return List.of();
    }

    public Collection<OracleColumnText> columnText() {
        if (this instanceof OracleCollectionTableSharedText shared) {
            return shared.getContents() == null ? List.of() : shared.getContents().values();
        }
        if (this instanceof OracleCollectionTableSharedRolls shared) {
            return shared.getContents() == null ? List.of() : shared.getContents().values();
        }
        return List.of();
    }

}
